spring:
  datasource:
    username: postgres
    password: 112358
    url: jdbc:postgresql://localhost/javid
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: true

    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql


